### ISSUE TITLE
NaCl minimum, optimum and maximum characters pulling out % values not related to NaCl

### ISSUE THREAD

**Issue by lmoore207** [biosemantics/micropie2#44] opened 2016-05-28 03:24 UTC
Sometimes the value(s) in the NaCl minimum, optimum and/or maximum characters are percentage values associated with mol% G+C or with percentages associated with fatty acid types. This doesn't occur all the time, but has occurred when the NaCl value is also presented. For example, I've seen NaCl minimum value as "40 mol%" taken from the sentence "The G + C content of the DNA is 40 mol% for the type strain " 

For an example from fatty acid percentages, the values "23 %#6 %#8 %#14 %#0.5 % artificial seawater;	1 % NaCl;	29 %#9 %#11 %#21 %#1.5 % artificial seawater" were extracted from the following text:
"The major isoprenoid quinone is MK-7.  The predominant cellular fatty acids are 15:0 iso (23–29 %), iso 17:19c (6–9 %), 17:0 iso 3-OH (8–11 %) and a mixture of 16:17c and 15:0 iso 2-OH (14–21 %).  DNA G+ C content is 37–42 mol%.  Many phenotypic characters differentiate this genus from related taxa (Table 3).  Phylogenetically, the genus belongs to the family Cytophagaceae.  The type species is Hongiella mannitolivorans. Cells are approximately 1.1–1.7 x 0.4–0.5 µm.  Colonies are convex, opaque and orange on MA.  Optimal growth is observed at 35–40 ˚C, pH 7 and 1% NaCl or 0.5–1.5% artificial sea salts.  Grows without NaCl or sea salts." 
The values should be "1 % NaCl # 0.5–1.5% artificial sea salts" for NaCl optimum only.

**Comment by carrineblank** [comment] 2016-06-09 16:27
This is related to Issue #38 - same problem.....

**Comment by danveno** [comment] 2016-06-30 22:04
The GC values are distinguished from the NaCl values, e.g. in this sentence. "The G + C content of the DNA is 40 mol% for the type strain " .

However, the fatty acid percentages sentences are classified into the NaCL, caused by the Character Predictors, This is an error which should be addressed in next version of MicroPIE. Two strategies may be applied: 1) improve the performance of classifiers to distinguish NaCl Values and fatty acid percentages. 2) add some specific rules for NaCL characters.

**Closed by danveno** 2016-06-30 22:04 UTC
